### ISSUE TITLE
Support FTPS connection to protect account credidentials

### ISSUE THREAD

**Issue by wna-se** [usegalaxy-eu/ena-upload-cli#48] opened 2021-12-02 14:33 UTC
The FTP protocol does not support secure connections between the client and the server and account credentials are sent as plain text. This might not be an issue depending on how the traffic is routed but it not good practice for general use cases.

**Comment by bedroesb** [comment] 2021-12-02 15:10
Thank you @wna-se for this suggetsion! I was looking into the `pysftp` library myself at the moment. But for sure this is something that has to be done

**Comment by bedroesb** [comment] 2021-12-03 10:10
I take my command back, we are off course talking about ftps, not sftp!

**Comment by bedroesb** [comment] 2021-12-03 15:02
@wna-se I added the TLS connection in #50, but your solution for transferring data straight from nextcloud to ENA ftp is actually also very interesting and something to think about! Would you be willing to help implementing this feature?

Thank you very much for opening this issue and sharing this info with us

**Comment by rabuono** [comment] 2021-12-03 15:35
@wna-se I would like to reiterate that the transferring of data straight from nextcloud to ENA does sound like an interesting solution.
Before I jump into trying to understand rclone:  in the solution you described, when is the md5 calculated? Before uploading the files to one's nextcloud? When setting up the transfer to ENA?

**Comment by wna-se** [comment] 2021-12-03 16:46
@rabuono The md5 is calculated as the data is transferred from Nextcloud to the FTP. Not something I would recommend if you can do it any other way but it was an interesting exercise in exploring ftplib and helpful in a specific case where memory, storage and CPU load was in relatively short supply.

**Comment by bedroesb** [comment] 2021-12-20 16:05
I will close this issue since the original purpose of the issue is tackled in #50, we can always open a feature request issue to support transferring data from Nextcloud.

**Closed** 2021-12-20 16:07 UTC
